# Generated by Django 3.2.9 on 2021-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FIC', 'fiction'), ('NFC', 'fiction')], max_length=3),
        ),
    ]
