# Generated by Django 3.2.9 on 2021-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FIC', 'fiction'), ('NFC', 'non-fiction')], max_length=3),
        ),
    ]
