# Generated by Django 3.2.9 on 2021-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
