# Generated by Django 3.2.9 on 2021-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20211125_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='', max_length=255),
        ),
    ]
